---
title: "linear models"
output: github_document
---

```{r setup}
library(tidyverse)
library(p8105.datasets)
```

## import data

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars,borough, neighborhood, room_type)



data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, neighborhood, room_type)

```

## fit a model

```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price, color = borough)) + 
  geom_point()
```

Let's fit the model
```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

Let's look at the results

```{r, include = FALSE}
fit

summary(fit)

summary(fit)$coef

coef(fit)

residuals(fit)
```

On this the model chooses variables alphabetically so Bronx is the reference

Let's look at the results better 

```{r}
broom::glance(fit)

broom::tidy(fit) %>% 
  select(-std.error, statistic) %>% 
  mutate(
    term = str_replace(term, "borough", "Borough: ")
  ) %>% 
  knitr::kable(digits = 3)
  
```

## Be in control of factors

```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(borough = fct_infreq(borough),
         room_type = fct_infreq(room_type)
  )
  

```

Look at that plot again

```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price, color = borough)) + 
  geom_point()
```

Refit model

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)

broom::tidy(fit)
broom::glance(fit)
```

##diagnostics

modelr- added column for residuals, 9.47 higher than what my model predicts, etc. 
```{r}
residuals(fit)

modelr::add_residuals(nyc_airbnb, fit)
```

